### ISSUE TITLE
Auto answer

### ISSUE THREAD

**Issue by mmarchjr** [mmccall0813/answer.js#2]
It doesn't auto answer on crypto hack. I was using a troll blooket, here is the link to it: https://www.blooket.com/set/5fab0d3a5bbc690004326d35

**Comment by mmccall0813** [comment]
This is basically impossible for me to fix given the way the blooket is made. Think of my script as a really fast thinking human player with an answer key. The same way a human player, even with an answer key, can't get all answers correct when the answer buttons are all blank, my script can't. The script works best on blookets with unique question names (non repeating) and unique question answers (no answers being the same).
