### ISSUE TITLE
Auto join code

### ISSUE THREAD

**Issue by oliver408i** [mmccall0813/answer.js#3]
I see that you are using the fb.blooket.com, but when I use the 
```
fetch("https://fb.blooket.com/c/firebase/join", {
        "body": `{\"id\":\"886005\",\"name\":\"answerdotjs\"}`,
        "method": "PUT",
        "mode": "cors"})
```
It doesn't work. Did blooket patch this or does it still work? I am also trying to make a flood and I wonder if you know how to automatically join. Thanks in advance! (i'll credit you if I even make the flooder, and I starred this repo)

**Comment by mmccall0813** [comment]
This endpoint doesn't actually make you join the game, it just returns basic info about the game, like the mode, set ID, and if the game is timed or ends on a game factor.

**Comment by oliver408i** [comment]
Hmm. Do you know how to make a bot join?

**Comment by mmccall0813** [comment]
No, I haven't really looked into it. You could try inspecting network traffic in the Network tab of your browsers devtools and make a simple joiner from there.

**Comment by justme1919** [comment]
cool
