### ISSUE TITLE
Add a hack for deceptive dino

### ISSUE THREAD

**Issue by justme1919** [mmccall0813/answer.js#4]
Add bc my teacher always put the gamemode.

**Comment by justme1919** [comment]
and i you could, can you add for all of gamemodes.

**Comment by justme1919** [comment]
_One star if you do it _

**Comment by justme1919** [comment]
_one star for you_

**Comment by justme1919** [comment]
`?add 1 star for mmccall0813 (all repositorys)`

**Comment by justme1919** [comment]
> 

umm

**Comment by justme1919** [comment]
[github.com/virus](url)

**Comment by justme1919** [comment]
[Github.com/virus CLICK NOW](gardensrestaurantandcatering.com)

**Comment by mmccall0813** [comment]
I'll mess around with it when I get free time tomorrow.

**Comment by justme1919** [comment]
ok
