### ISSUE TITLE
No longer works on battle royale

### ISSUE THREAD

**Issue by yibbbbbb** [mmccall0813/answer.js#5]

**Comment by justme1919** [comment]
How?

**Comment by justme1919** [comment]
?

**Comment by justme1919** [comment]
`Sudo//JAVA (battle royale) WORKS`

**Comment by justme1919** [comment]
Oh 😒😒😒😒 it doesn't work

**Comment by yibbbbbb** [comment]
It no longer answers the questions at all

**Comment by mmccall0813** [comment]
yeah my bad on this one, forgot to copy over the question code for battle royale when I improved question matching. I will fix soon

**Comment by justme1919** [comment]
ok
