### ISSUE TITLE
Fishing frenzy auto answer dosnt work

### ISSUE THREAD

**Issue by yibbbbbb** [mmccall0813/answer.js#6]
It casts but dosnt answer the question

**Comment by mmccall0813** [comment]
Could you possibly link the set that you used? I can't seem to replicate this issue.

**Comment by yibbbbbb** [comment]
This is the set in question 

https://www.blooket.com/set/614ccc58917a77002afc86b7

**Comment by mmccall0813** [comment]
Fixed!
